<?php

namespace Tests\Feature;

use App\Restrictions\RestrictionTableBuilder;
use App\Services\RestrictionsService;
use App\Support\LocationSlug;
use Tests\TestCase;

/**
 * Parity tests: PHP RestrictionTableBuilder output must match the golden
 * *.viewmodel.json fixtures generated by the TypeScript buildFishTables pipeline.
 *
 * Golden fixtures are regenerated with:  npm run export-restriction-fixtures
 *
 * Date comparison uses only the calendar date (YYYY-MM-DD) to avoid
 * timezone differences between JS and PHP serialization.
 */
class RestrictionTableParityTest extends TestCase
{
	private const FIXTURES_DIR = __DIR__ . '/../fixtures/restrictions';

	// ── helpers ──────────────────────────────────────────────────────────────

	/** Load a *.viewmodel.json golden fixture. */
	private function loadGoldenViewmodel(string $name): array
	{
		$path = self::FIXTURES_DIR . "/{$name}.viewmodel.json";
		$this->assertFileExists($path, "Golden viewmodel fixture missing: {$name}.viewmodel.json. Run: npm run export-restriction-fixtures");
		return json_decode(file_get_contents($path), true);
	}

	/** Load a *.raw.json fixture and extract context. */
	private function loadRawContext(string $name): array
	{
		$path = self::FIXTURES_DIR . "/{$name}.raw.json";
		$this->assertFileExists($path, "Raw fixture missing: {$name}.raw.json");
		return json_decode(file_get_contents($path), true);
	}

	/** Extract YYYY-MM-DD from an ISO string like "2026-05-01T12:00:00+00:00". */
	private function dateOnly(?string $iso): ?string
	{
		if ($iso === null) {
			return null;
		}
		return substr($iso, 0, 10);
	}

	/**
	 * Sort table rows by a stable canonical key so that two rows whose sort
	 * order is undefined in the TypeScript comparator (e.g. two records that
	 * both have a non-empty `tidal` field but identical seasonStart) still
	 * compare equal regardless of which JS/PHP sort implementation was used.
	 *
	 * The key is: kind, then seasonStart date, then seasonEnd date.
	 */
	private function stableSortRows(array $rows): array
	{
		usort($rows, function (array $a, array $b): int {
			$kindCmp = strcmp((string) ($a['kind'] ?? ''), (string) ($b['kind'] ?? ''));
			if ($kindCmp !== 0) {
				return $kindCmp;
			}
			$startCmp = strcmp(
				$this->dateOnly($a['seasonStart'] ?? null) ?? '',
				$this->dateOnly($b['seasonStart'] ?? null) ?? '',
			);
			if ($startCmp !== 0) {
				return $startCmp;
			}
			return strcmp(
				$this->dateOnly($a['seasonEnd'] ?? null) ?? '',
				$this->dateOnly($b['seasonEnd'] ?? null) ?? '',
			);
		});
		return $rows;
	}

	/**
	 * Compare two viewmodel shapes: fish table count, fish names, row counts,
	 * and key date/limit values in each row.
	 *
	 * Rows within each fish table are sorted by (kind, seasonStart, seasonEnd)
	 * before comparison so that undefined sort order between records with
	 * identical constraints does not cause spurious failures.
	 *
	 * We intentionally do NOT compare the full `verify` field (contains raw
	 * record data that differs in field structure between PHP and TS).
	 */
	private function assertViewmodelParity(array $expected, array $actual, string $context): void
	{
		$this->assertCount(
			count($expected['fishTables']),
			$actual['fishTables'],
			"{$context}: fish table count mismatch",
		);

		foreach ($expected['fishTables'] as $i => $expectedTable) {
			$actualTable = $actual['fishTables'][$i];
			$fish = $expectedTable['fishName'];

			$this->assertSame($expectedTable['fishName'], $actualTable['fishName'], "{$context}: fishTables[{$i}] fishName");
			$this->assertCount(
				count($expectedTable['rows']),
				$actualTable['rows'],
				"{$context}: {$fish} row count",
			);

			$expectedRows = $this->stableSortRows($expectedTable['rows']);
			$actualRows   = $this->stableSortRows($actualTable['rows']);

			foreach ($expectedRows as $j => $expectedRow) {
				$actualRow = $actualRows[$j];
				$rowId = "{$context}: {$fish} row[{$j}]";

				$this->assertSame($expectedRow['kind'], $actualRow['kind'], "{$rowId} kind");

				if ($expectedRow['kind'] === 'data') {
					$this->assertSame(
						$this->dateOnly($expectedRow['seasonStart']),
						$this->dateOnly($actualRow['seasonStart']),
						"{$rowId} seasonStart",
					);
					$this->assertSame(
						$this->dateOnly($expectedRow['seasonEnd']),
						$this->dateOnly($actualRow['seasonEnd']),
						"{$rowId} seasonEnd",
					);
					$this->assertSame($expectedRow['bagLimit'], $actualRow['bagLimit'], "{$rowId} bagLimit");
					$this->assertSame($expectedRow['hookLimit'], $actualRow['hookLimit'], "{$rowId} hookLimit");
					$this->assertSame($expectedRow['minSize'], $actualRow['minSize'], "{$rowId} minSize");
					$this->assertSame($expectedRow['maxSize'], $actualRow['maxSize'], "{$rowId} maxSize");
					$this->assertSame($expectedRow['bagLimitShowInfinity'], $actualRow['bagLimitShowInfinity'], "{$rowId} bagLimitShowInfinity");
					$this->assertSame($expectedRow['isExceptionRow'], $actualRow['isExceptionRow'], "{$rowId} isExceptionRow");
					$this->assertSame($expectedRow['exceptionNoteSpan'], $actualRow['exceptionNoteSpan'], "{$rowId} exceptionNoteSpan");
					$this->assertSame($expectedRow['showExceptionLimitCells'], $actualRow['showExceptionLimitCells'], "{$rowId} showExceptionLimitCells");
					$this->assertSame($expectedRow['hideBagLimit'], $actualRow['hideBagLimit'], "{$rowId} hideBagLimit");
					$this->assertSame($expectedRow['hideMinSize'], $actualRow['hideMinSize'], "{$rowId} hideMinSize");
					$this->assertSame($expectedRow['hideMaxSize'], $actualRow['hideMaxSize'], "{$rowId} hideMaxSize");
					$this->assertSame($expectedRow['dateTrailingComma'], $actualRow['dateTrailingComma'], "{$rowId} dateTrailingComma");
					$this->assertSame($expectedRow['showLocationDetail'], $actualRow['showLocationDetail'], "{$rowId} showLocationDetail");
					$this->assertSame($expectedRow['waterGroupContinue'] ?? false, $actualRow['waterGroupContinue'] ?? false, "{$rowId} waterGroupContinue");
				}
			}
		}

		$this->assertCount(
			count($expected['undatedExceptions']),
			$actual['undatedExceptions'],
			"{$context}: undatedExceptions count",
		);
	}

	// ── tests ─────────────────────────────────────────────────────────────────

	public function test_chaleur_bass_river_parity_against_golden_fixture(): void
	{
		$context = 'chaleur-bass-river';
		$rawContext = $this->loadRawContext($context);
		$waterId = $rawContext['_context']['waterId'] ?? null;
		$golden = $this->loadGoldenViewmodel($context);

		try {
			$regionModel = LocationSlug::findRegion('chaleur');
		} catch (\Exception $e) {
			$this->markTestSkipped("DB not available ({$e->getMessage()})");
		}

		if (!$regionModel) {
			$this->markTestSkipped('Region "chaleur" not found — requires migrated MySQL database.');
		}

		try {
			$waterModel = LocationSlug::findWater('bass-river', $regionModel->id);
		} catch (\Exception $e) {
			$this->markTestSkipped("DB not available ({$e->getMessage()})");
		}

		if (!$waterModel) {
			$this->markTestSkipped('Water "bass-river" not found — requires migrated MySQL database.');
		}

		$service = app(RestrictionsService::class);
		$limits = $service->getByRegionAndWater($regionModel->id, $waterModel->id);

		$actual = RestrictionTableBuilder::build($limits, ['waterId' => $waterId]);

		$this->assertViewmodelParity($golden, $actual, $context);
	}

	public function test_chaleur_region_parity_against_golden_fixture(): void
	{
		$context = 'chaleur';
		$golden = $this->loadGoldenViewmodel($context);

		try {
			$regionModel = LocationSlug::findRegion('chaleur');
		} catch (\Exception $e) {
			$this->markTestSkipped("DB not available ({$e->getMessage()})");
		}

		if (!$regionModel) {
			$this->markTestSkipped('Region "chaleur" not found — requires migrated MySQL database.');
		}

		$service = app(RestrictionsService::class);
		$limits = $service->getByRegion($regionModel->id);

		$actual = RestrictionTableBuilder::build($limits, ['waterId' => null]);

		$this->assertViewmodelParity($golden, $actual, $context);
	}

	/**
	 * Fixture-only parity test: runs without a database by using the raw
	 * fixture data to construct NormalizedRecord objects directly.
	 * This exercises the full PHP pipeline without requiring MySQL.
	 */
	#[\PHPUnit\Framework\Attributes\Group('fixture-only')]
	public function test_chaleur_bass_river_parity_from_raw_fixture(): void
	{
		$rawContext = $this->loadRawContext('chaleur-bass-river');
		$golden = $this->loadGoldenViewmodel('chaleur-bass-river');

		$limits = $rawContext['limits'] ?? [];
		if (empty($limits)) {
			$this->markTestSkipped('Raw fixture is empty.');
		}

		$waterId = $rawContext['_context']['waterId'] ?? null;

		// Build using normalizeFromArray (JSON rows, not Eloquent models)
		$normalized = array_map(
			fn(array $row) => \App\Restrictions\RecordNormalizer::fromArray($row),
			$limits,
		);

		$actual = \App\Restrictions\RestrictionTableBuilder::buildFromNormalized($normalized, ['waterId' => $waterId]);

		$this->assertViewmodelParity($golden, $actual, 'chaleur-bass-river (fixture-only)');
	}
}
